services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: venmitodb
    hostname: localhost
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=venmitodb
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data