FROM python:3.9-slim

WORKDIR /app

# Copy the same requirements_ui.txt or a separate file if needed
COPY requirements_streamlit.txt .
RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "streamlit_app.py"]